name: Docker Build

on:
#  push:
#    branches:
#      - 'master'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: write
    strategy:
      matrix:
        oort-version: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (Emulation for ARM & Other Architectures)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: thecaliskan
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thecaliskan
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: thecaliskan
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Log in to QUAY
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Run Docker Container and Extract PHP Extensions
        run: |
          docker run --rm thecaliskan/oort:${{ matrix.oort-version }} \
          php -r 'echo json_encode(array_map(fn($ext) => ["name" => $ext, "version" => phpversion($ext) ?: "Unknown"], get_loaded_extensions()), JSON_PRETTY_PRINT);' \
          > php-extensions-${{ matrix.oort-version }}.json

      - name: Upload PHP Extensions as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-extensions
          path: ./php-extensions-**.json

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.oort-version }}
          path: ./output/**/sbom.spdx.json

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.output.json

      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sarif-${{ matrix.oort-version }}
          path: sarif.output.json

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger docs workflow
        run: gh workflow run pages.yml --repo thecaliskan/oort-docs --ref master
        env:
          GITHUB_TOKEN: ${{ secrets.OORT_GITHUB_TOKEN }}