name: Docker Build

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        oort-version: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (Emulation for ARM & Other Architectures)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          TAGS="-t thecaliskan/oort:${{ matrix.oort-version }}"
          GHCR_TAGS="-t ghcr.io/${{ github.repository_owner }}/oort:${{ matrix.oort-version }}"
          
          if [ "${{ matrix.oort-version }}" == "8.4" ]; then
            TAGS="$TAGS -t thecaliskan/oort:latest"
            GHCR_TAGS="$GHCR_TAGS -t ghcr.io/${{ github.repository_owner }}/oort:latest"
          fi
          
          # Push to GitHub Container Registry
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x \
            --build-arg OORT_VERSION=${{ matrix.oort-version }} \
            $GHCR_TAGS \
            --push .
          
          # Push to Docker Hub
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x \
            --build-arg OORT_VERSION=${{ matrix.oort-version }} \
            $TAGS \
            --push .