name: Docker Build

on:
  push:
    branches:
      - 'docker'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  docs-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs workflow
        run: gh workflow run pages.yml --repo thecaliskan/oort-docs --ref master